optuna:
  trials: 20
  n_estimators:
    min: 50
    max: 150
    step: 10
  max_depth:
    min: 2
    max: 15
  min_samples_split:
    min: 2
    max: 10
  min_samples_leaf:
    min: 2
    max: 10
bento:
  model_name: medical_regressor
  model_tag: random_forest
cv:
  n_splits: 10
  shuffle: true
model:
  features:
    cat:
      - sex
      - smoker
      - region
    rest:
      - age
      - bmi
      - children