stages:
  - process_data
  - train_model
  - register_model
  - deploy

preprocessing:
  stage: process_data
  image: python:3.12
  before_script:
    - cd project
    - pip install poetry
    - poetry install --no-interaction --no-ansi
  script:
    - poetry run python src/data/fetch_data.py
    - poetry run python src/data/split_data.py
  artifacts:
    paths:
      - data/processed/

training:
  stage: train_model
  image: python:3.12
  before_script:
    - cd project
    - pip install poetry
    - poetry install
  script:
    - poetry run python src/mlflow_setup.py
    - poetry run python src/main.py

building:
  stage: register_model
  image: python:3.12
  before_script:
    - cd project
    - pip install poetry
    - poetry install
  script:
    - poetry run python src/project/server/build_model.py

deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
    - eval $(ssh-agent -s)
    - echo "$VPS_SECRET_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/*
    - ssh-keyscan -p $SSH_PORT "$VPS_HOST" >> ~/.ssh/known_hosts
    - echo -e "Host $VPS_HOST\n\tUser $SSH_USER\n\tStrictHostKeyChecking no\n\tPort $SSH_PORT\n" > ~/.ssh/config

  script:
    - scp -P $SSH_PORT project/docker-compose.yaml $SSH_USER@$VPS_HOST:/opt/user/
    - ssh -p $SSH_PORT "$SSH_USER@$VPS_HOST" "
        docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com &&
        docker-compose -f /opt/user/docker-compose.yaml pull &&
        docker-compose -f /opt/user/docker-compose.yaml up -d
      "

  only:
    - main