stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
    - eval $(ssh-agent -s)
    - echo "$VPS_SECRET_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/*
    - ssh-keyscan "$VPS_HOST" >> ~/.ssh/known_hosts
    - echo -e "Host $VPS_HOST\n\tUser $SSH_USER\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

  script:
    - scp project/docker-compose.yaml $SSH_USER@$VPS_HOST:/home/user/
    - ssh "$SSH_USER@$VPS_HOST" "
        docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com &&
        docker-compose -f /home/user/docker-compose.yaml pull &&
        docker-compose -f /home/user/docker-compose.yaml up -d
      "

  only:
    - main