stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
    - wget -qO- https://get.docker.com/gpg | apt-key add -
    - eval $(ssh-agent -s)
    - echo "$VPS_SECRET_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/*
    - ssh-keyscan "$VPS_HOST" >> ~/.ssh/known_hosts
    - '[[ -f /.dockerinit ]] && echo -e "Host $VPS_HOST\n\tUser $SSH_USER\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - docker-compose -f docker-compose.yaml up -d

  only:
    - main