version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8000:3000
    environment:
      - BENTO_PORT=3000

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8001:8501
    environment:
      - BENTO_PORT=3000
      - BENTO_HOST=server
    depends_on:
      - server
    entrypoint: /app/entrypoint.sh
